pulse_stack:
  outputs:
    dev:
      type: postgres
      host: pulse-postgres
      user: admin
      password: admin
      port: 5432
      dbname: healthcare
      schema: bronze
      threads: 4
      keepalives_idle: 0
      search_path: "bronze"
    
    prod:
      type: postgres
      host: pulse-postgres
      user: admin
      password: admin
      port: 5432
      dbname: healthcare
      schema: bronze
      threads: 10
      keepalives_idle: 0
      search_path: "bronze"
  
  target: dev
