version: 2

sources:
  - name: staging
    description: "Source for staging data from MinIO"
    database: healthcare
    schema: bronze
    tables:
      - name: _airbyte_raw_patients
        description: "Informations sur les patients"
