version: 2

sources:
  - name: bronze
    description: "Bronze layer - Raw data from MinIO via Airbyte"
    schema: public
    tables:
      - name: patients
        description: "Raw healthcare patient data from SPARCS"
        columns:
          - name: "Health Service Area"
            description: "Geographic health service area"
          - name: "Hospital County"
            description: "County where hospital is located"
          - name: "Operating Certificate Number"
            description: "Hospital operating certificate number"
          - name: "Facility Id"
            description: "Hospital facility identifier"
          - name: "Facility Name"
            description: "Hospital facility name"
          - name: "Age Group"
            description: "Patient age group"
          - name: "Zip Code - 3 digits"
            description: "First 3 digits of patient zip code"
          - name: "Gender"
            description: "Patient gender"
          - name: "Race"
            description: "Patient race"
          - name: "Ethnicity"
            description: "Patient ethnicity"
          - name: "Length of Stay"
            description: "Number of days in hospital"
          - name: "Type of Admission"
            description: "Type of hospital admission"
          - name: "Patient Disposition"
            description: "Where patient went after discharge"
          - name: "Discharge Year"
            description: "Year of discharge"
          - name: "CCS Diagnosis Code"
            description: "Clinical Classification Software diagnosis code"
          - name: "CCS Diagnosis Description"
            description: "Clinical Classification Software diagnosis description"
          - name: "CCS Procedure Code"
            description: "Clinical Classification Software procedure code"
          - name: "CCS Procedure Description"
            description: "Clinical Classification Software procedure description"
          - name: "APR DRG Code"
            description: "All Patient Refined Diagnosis Related Group code"
          - name: "APR DRG Description"
            description: "All Patient Refined Diagnosis Related Group description"
          - name: "APR MDC Code"
            description: "All Patient Refined Major Diagnostic Category code"
          - name: "APR MDC Description"
            description: "All Patient Refined Major Diagnostic Category description"
          - name: "APR Severity of Illness Code"
            description: "APR severity of illness code"
          - name: "APR Severity of Illness Description"
            description: "APR severity of illness description"
          - name: "APR Risk of Mortality"
            description: "APR risk of mortality"
          - name: "APR Medical Surgical Description"
            description: "APR medical or surgical description"
          - name: "Payment Typology 1"
            description: "Primary payment method"
          - name: "Payment Typology 2"
            description: "Secondary payment method"
          - name: "Payment Typology 3"
            description: "Tertiary payment method"
          - name: "Birth Weight"
            description: "Birth weight in grams"
          - name: "Abortion Edit Indicator"
            description: "Abortion edit indicator"
          - name: "Emergency Department Indicator"
            description: "Emergency department indicator"
          - name: "Total Charges"
            description: "Total charges for treatment"
          - name: "Total Costs"
            description: "Total costs for treatment"